### PR TITLE
Add more endpoints

### PR DESCRIPTION
**Pull request by lpgauth**
I added a few endpoints I needed to run Cloud Agent on a servers outside GCP.

### CODE REVIEW

**Comment by salrashid123** [comment]
thanks for this, just some comments

Maybe its time to consider implementing arbitrary metadata as a directory structure 

  https://github.com/salrashid123/gce_metadata_server/tree/master?tab=readme-ov-file#todo



i'd recommed comparing changes to live gce metadata server to verify (eg, response headers are text (they should be), the 404's for unknown attributes and the paths match


---

anyway

* A) `enable-osconfig`

```golang
r.Handle("/computeMetadata/v1/instance/attributes/enable-osconfig", http.HandlerFunc(enableOsConfig)).Methods(http.MethodGet)
```

 does adding in `enable-guest-attributes` too? if not, i can add it later



---

C) `network-interfaces`


```golang
r.Handle("/computeMetadata/v1/instance/network-interfaces/", http.HandlerFunc(networkInterfacesRootHandler)).Methods(http.MethodGet)
r.Handle("/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/{key}", http.HandlerFunc(networkInterfacesAccessConfigHandler)).Methods(http.MethodGet)
```

what about support for multiple interfaces?

i think to accomodate this the directory structure parsing cited above would be better long term.  I can fiddle with that to see if i can make it work as a sample

```
$ curl -s -H 'Metadata-Flavor: Google'  http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/
0/
1/

~$ curl -s -H 'Metadata-Flavor: Google'  http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/
0/


$ curl -s -H 'Metadata-Flavor: Google'  http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/
access-configs/
dns-servers
forwarded-ips/
gateway
ip
ip-aliases/
mac
mtu
network
subnetmask
target-instance-ips
```


---

D) `external-ip`

the path shiould be different

```golang
r.Handle("/computeMetadata/v1/instance/network-interfaces/0/{key}", http.HandlerFunc(networkInterfacesHandler)).Methods(http.MethodGet)
```

```
$ curl -s -H 'Metadata-Flavor: Google'  http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip
35.188.94.214
```

**Comment by lpgauth** [comment]
Thanks for the review, I should get around to update the PR next week.

**Comment by salrashid123** [comment]
can you hold off on the PR for a bit?  

i'm trying to see if there's a way to re-design the serving part alltogether to use a combo of static stuff defined in a filesystem stuff and dynamic stuff (for tokens, etc)

basically  this [todo](https://github.com/salrashid123/gce_metadata_server?tab=readme-ov-file#todo)


---

i looked at it in a bit now and will need to look further 

I defined a static file from root like this

```bash
$ tree
.
└── static
    └── computeMetadata
        └── v1
            └── instance
                └── network-interfaces
                    └── 0
                        └── access-configs
                            └── 0
                                ├── external-ip
                                └── type
```

where the filesystem matches the strcutre of the metadata server responses

```                                
$ cat static/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip 
34.69.160.1
```

which on a live metadata server gives

```bash
$ curl -v -H 'Metadata-Flavor: Google' http://metadata/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip

< HTTP/1.1 200 OK
< Metadata-Flavor: Google
< Content-Type: application/text
< ETag: ca5562c7dbe44d84
< Date: Wed, 10 Jan 2024 16:05:43 GMT
< Server: Metadata Server for VM
< Content-Length: 11
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
< 
* Connection #0 to host metadata left intact
34.69.160.1
```

all that is done by a setting overrides


```golang
// r.Handle("/computeMetadata/v1/instance/", http.HandlerFunc(instanceHandler)).Methods(http.MethodGet)
// r.Handle("/computeMetadata/v1/instance/{key}", http.HandlerFunc(instancev1PathHandler)).Methods(http.MethodGet)

r.Handle("/computeMetadata/v1/instance", http.HandlerFunc(instanceRedirectHandler)).Methods(http.MethodGet)
r.PathPrefix("/computeMetadata/v1/instance/").Handler(http.FileServer(http.Dir("static/")))
```


the "problem" i'm seeing so far is with directory browsing:
    the `content-type` and payload gorrilla mux returns is `html` for directory browsing while the actual metadata server returns text:

- actual metadata server:

```bash
$ curl -v -H 'Metadata-Flavor: Google' http://metadata/computeMetadata/v1/instance/

< HTTP/1.1 200 OK
< Metadata-Flavor: Google
< Content-Type: application/text    <<<<<<<<<<<<<<<<<
< ETag: fb3e214bc1dc99bc
< Date: Wed, 10 Jan 2024 16:54:00 GMT
< Server: Metadata Server for VM
< Content-Length: 250
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
< 

network-interfaces/
```


- gorilla mux:

```bash
$ curl -v -H 'Metadata-Flavor: Google' --connect-to metadata.google.internal:80:127.0.0.1:8080    http://metadata.google.internal/computeMetadata/v1/instance/

< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< Last-Modified: Wed, 10 Jan 2024 16:34:02 GMT
< Metadata-Flavor: Google
< Server: Metadata Server for VM
< X-Frame-Options: 0
< X-Xss-Protection: 0
< Date: Wed, 10 Jan 2024 16:55:17 GMT
< Content-Length: 67
< 
<pre>
<a href="network-interfaces/">network-interfaces/</a>
</pre>
```

**Comment by salrashid123** [comment]
@lpgauth 

sorry for the delay...it took sometime  to workaround and find some way to accomodate the real metadata server's nuances.

i'm thinking of updating the metadata server entirely and include your changes.

The following basically reads a full json config files with all the attributes set and fulfils the exsiting and the PR you've submitted (for network-interfaces)

there are many odd thing  in the server below (content-types, path redirects, json/text, etc)...but all those are just what the actul server does.

PTAL and let me know if this seems ok and i'll update the master branch


to use, basically make a copy of `config.json` and `main.go` and run it...the metadta server reads the values from config.json  but the access and identity tokens are live from a service account

https://gist.github.com/salrashid123/469e18dbb0a771719273b2c255c01be8

**Comment by salrashid123** [comment]
please check the latest release...i included changes which surfaces the endpoint your'e looking for.

  if it looks ok,  pls close this out

**Pull request closed without merging**
